<p style="font-family: Arial; font-size:3.75em;color:purple; font-style:bold"><br>
Introduction to Numpy:
</p><br>

<p style="font-family: Arial; font-size:1.25em;color:#2462C0; font-style:bold"><br>
Package for scientific computing with Python
</p><br>

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Additional Common ndarray Operations
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Dot Product on Matrices and Inner Product on Vectors:

</p>

In [2]:
import numpy as np
# determine the inner product of two vectors
a1d = np.array([9,9])
b1d = np.array([10,10])
np.dot(a1d,b1d)

180

In [3]:
# determine the dot product of two matrices
a2d = np.array([[1,2],[3,4]])
b2d = np.array([[2,3],[4,5]])
np.dot(a2d,b2d)
a2d.dot(b2d)

array([[10, 13],
       [22, 29]])

array([[10, 13],
       [22, 29]])

In [4]:
# dot produce of an array and vector
np.dot(a2d,a1d)

array([27, 63])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Element-wise Functions: </p>

For example, let's compare two arrays values to get the maximum of each.

In [5]:
# random array
x = np.random.randn(8)
x

array([-0.41037157,  0.11415822,  0.84107638, -1.54219984,  1.29506974,
        0.71069947, -0.87030071,  0.14140779])

In [6]:
# another random array
y = np.random.randn(8)
y

array([-0.77028155, -0.5501558 , -0.62698416,  1.08328845,  0.14512142,
       -0.30222428,  2.27869328, -1.18122302])

In [7]:
# returns element wise maximum between two arrays
np.maximum(x,y)

array([-0.41037157,  0.11415822,  0.84107638,  1.08328845,  1.29506974,
        0.71069947,  2.27869328,  0.14140779])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Reshaping array:
</p>

In [8]:
# grab values from 0 through 19 in an array and reshape to be a 4 x 5 matrix
grid = np.arange(20).reshape(4,5)
print(grid)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Transpose:

</p>

In [9]:
# transpose
grid.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Merging data sets:
</p>

In [10]:
#Creating two arrays
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[ 2 49]
 [34 35]]

[[11 30]
 [27 39]]


In [11]:
#vertical merge
np.vstack((K,M))

array([[ 2, 49],
       [34, 35],
       [11, 30],
       [27, 39]])

In [12]:
#horizontal merge
np.hstack((K,M))

array([[ 2, 49, 11, 30],
       [34, 35, 27, 39]])

In [13]:
#using concatenate, vertical merge -> axis = 0
np.concatenate([K,M], axis = 0)

array([[ 2, 49],
       [34, 35],
       [11, 30],
       [27, 39]])

In [14]:
#using contenate
np.concatenate([K,M], axis = 1)

array([[ 2, 49, 11, 30],
       [34, 35, 27, 39]])

<p style="font-family: Arial; font-size:3.75em;color:purple; font-style:bold"><br>
Introduction to Web Scraping:
</p><br>

In [1]:
#We need requests package and url
import requests
res = requests.get('https://automatetheboringstuff.com/files/rj.txt')
type(res)

requests.models.Response

In [2]:
#Check whether the request succeeds
res.status_code == requests.codes.ok

True

In [3]:
#Check the length of response
len(res.text)
print(res.text[:500])

The Project Gutenberg EBook of Romeo and Juliet, by William Shakespeare

This eBook is for the use of anyone anywhere at no cost and with
almost no restrictions whatsoever.  You may copy it, give it away or
re-use it under the terms of the Project Gutenberg License included
with this eBook or online at www.gutenberg.org/license


Title: Romeo and Juliet

Author: William Shakespeare

Posting Date: May 25, 2012 [EBook #1112]
Release Date: November, 1997  [Etext #1112]

Language: Eng


In [18]:
#Exceptions often happen when accessing websites. So it might be a good idea to catch errors
res = requests.get('http://automatetheboringstuff.com/page_that-does_not_exist')
res.raise_for_status()

HTTPError: 404 Client Error: Not Found for url: http://automatetheboringstuff.com/page_that-does_not_exist

In [4]:
#saving downloaded files
url = "http://www.yelp.com"

res = requests.get(url)
res.raise_for_status()
yelpfile = open('C:\\Users\\lxg180006\\Downloads\\yelp.html', 'wb')
yelpfile.write(res.content)
yelpfile.close()

print(res.text)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\lxg180006\\Downloads\\yelp.html'

In [19]:
import os
os.getcwd()

'C:\\Users\\lxg180006\\Downloads'

In [ ]:
#Using loop to write to advoide requests using too much memory, if you download massive files
url = "http://www.yelp.com"

res = requests.get(url)
res.raise_for_status()
yelpfile = open('C:\\Users\\lxg180006\\Downloads\\yelp.html', 'wb')
for chunk in res.iter_content(100000):
    yelpfile.write(chunk)
yelpfile.close()

print(res.text)

In [ ]:
#Parsing HTML with the BeautifulSoup Module
import bs4
res = requests.get(url)
res.raise_for_status()
yelpSoup = bs4.BeautifulSoup(res.text, 'html.parser')
type(yelpSoup)
print(yelpSoup)

In [8]:
import bs4
exampleFile = open('example.html')
exampleSoup = bs4.BeautifulSoup(exampleFile, 'html.parser')

FileNotFoundError: [Errno 2] No such file or directory: 'example.html'

In [5]:
#Finding elements with select() method - Find author
elems = exampleSoup.select('#author') # select('#author')返回一个列表，其中包含所有带有
#id=author 的元素
elems
type(elems)
elems[0].getText()
elems[0].attrs

NameError: name 'exampleSoup' is not defined

In [6]:
#Finding elements with select()-All paragraphs
pelems = exampleSoup.select('p')
pelems
pelems[0].getText()

NameError: name 'exampleSoup' is not defined

In [30]:
#To get the top stories from Google news
from bs4 import BeautifulSoup as soup

news_url = "https://news.google.com/news/rss"
res = requests.get(news_url)
res.raise_for_status
newspage = open('news.xml','wb')
for chunk in res.iter_content(100000):
    newspage.write(chunk)

soup_page = soup(open('news.xml'),'xml')
news_list = soup_page.select("item")

for news in news_list:
    print(news.title.text)
    print(news.link.text)
    print(news.pubDate.text)
    print("-*60")


<bound method Response.raise_for_status of <Response [200]>>

79007

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 47138: character maps to <undefined>

In [ ]:
#Download all XKCD comics - crawling from page to page


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Twitter API
</p>

In [31]:
#Installation
!pip install tweepy

  Running setup.py bdist_wheel for PySocks: started
  Running setup.py bdist_wheel for PySocks: finished with status 'done'
  Stored in directory: C:\Users\lxg180006\AppData\Local\pip\Cache\wheels\22\5c\b5\12e0dfdfa85bea67b23628b6425fae715c687e947a45ee3df9
Successfully built PySocks


You are using pip version 9.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [33]:
python -m pip install --upgrade pip

SyntaxError: invalid syntax (<ipython-input-33-93493bbcf27f>, line 1)

In [ ]:
import tweepy #https://github.com/tweepy/tweepy
 
#Twitter API credentials. You need to go to dev.twitter.com to create an account and create an app to get the
#credentials
consumer_key = "CS4G6dGaf7OCUTRRfRLO3bQB9"
consumer_secret = "hQgJkNg8r0BVh5YUzDEvVngOFGdxAPJvD9zA5cUi0BRc3Bi6SU"
access_key = "23432844-lXOod5aqMskdHz4wVR2asxThxTCvUWiHbUCqYq1b6"
access_secret = "UqZeg3EWCqC0h5hwGqN87xvzzY7OvGVZ7gCoIYMCNWnYX"

#Authorization with tweepy
auth = tweepy.OAuthHandler(consumer_key,consumer_secret)
auth.set_access_token(access_key,access_secret)
api = tweepy.API(auth)

#home_timeline() function Returns the 20 most recent statuses, including retweets, 
#posted by the authenticating user and that user’s friends.
public_tweets = api.home_timeline()
for tweet in public_tweets:
    print(tweet.text)

In [35]:
# Main Model classes in the Twitter API are Tweets, Users, Entities and Places. 
user = api.me()

print('Name: '+user.name)
print('Friends: '+str(user.friends_count))

Name: luoxuechen
Friends: 75


In [36]:
userPOTUS = api.get_user('realDonaldTrump')
print('Name: '+userPOTUS.name)
print('Friends: '+str(userPOTUS.friends_count))

Name: Donald J. Trump
Friends: 45


In [37]:
trump_tweets = api.user_timeline('realDonaldTrump')
for tweet in trump_tweets:
    print(tweet.text)

Senator John Cornyn has done an outstanding job for the people of Texas. He is strong on Crime, the Border, the Sec… https://t.co/gxJLXzB5Ax
.@JussieSmollett - what about MAGA and the tens of millions of people you insulted with your racist and dangerous comments!? #MAGA
THE WALL IS UNDER CONSTRUCTION RIGHT NOW! https://t.co/exUJCiITsz
....something that is so obviously the future. I want the United States to win through competition, not by blocking… https://t.co/hztqUt8v9S
I want 5G, and even 6G, technology in the United States as soon as possible. It is far more powerful, faster, and s… https://t.co/quvGzqNGpZ
I have instructed Secretary of State Mike Pompeo, and he fully agrees, not to allow Hoda Muthana back into the Country!
We have just built this powerful Wall in New Mexico. Completed on January 30, 2019 – 47 days ahead of schedule! Man… https://t.co/32ThjNvKoy
California now wants to scale back their already failed “fast train” project by substantially shortening the distan… ht

In [ ]:
import sys
import csv

#define a function to retrieve all tweets from an account
def get_all_tweets(screen_name):
    alltweets = []
    #make initial request for most recent tweets (200 is the maximum allowed count)
    new_tweets =api.user.timeline(screen_name = screen_name, count= 200) 

    #save most recent tweets
    alltweets.extend(new_tweets)  
    
    ## please remoember what is the difference betten extent and attend

    #save the id of the oldest tweet less one
    oldest = alltweets[-1]-1
    
   #keep grabbing tweets until there are no tweets left to grab
    while len(new_tweets)>0
       print("getting tweets before %s" % oldest)   ## here % means what ever afther the oldest , it will be presented by string 
    
     new_tweets =api.user_timeline(screen_name = screen_name, count = 200, max_id = oldest)
     alltweets. extend(new_tweets)
    
     oldest = alltweets[-1]-1
     print("...%s tweets downloaded so far" %(len(alltweets)))
    
    #transform the tweepy tweets into a list
    outtweets =[[tweet.id_str,tweet.created_at, tweet.text] for tweet in alltweets]
    return outtweets
    
    
    
    
    
    
    

In [ ]:
trumptweets = get_all_tweets('realDonaldTrump')

In [ ]:
#write to csv file 
with open('%s_tweets.csv'% screen_name, 'wb')as f:
    writer = csv.writer(f)
    writer.writerow(['id','created_at','text']) # write the first row
    writer.writerow(outtweets)
## How do we write the file:  everysingle
## %s means it is a variable. I am going to use the variable in this string. 
## for csv we have a writer function; 